apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: db-np
spec:
  podSelector:
    matchLabels:
      name: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: backend
    ports:
    - protocol: TCP
      port: 3306
