apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-box
  name: busy-box-2
spec:
  containers:
  - image: busybox:1.28
    name: busy-box
    command: ['sh','-c','echo The app is working && sleep 3600 ']
    envFrom:
    - configMapRef:
        name: app-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
