# this is a sample pod yaml
# labels are user defined key value
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: demo
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx1123
    ports:
    - containerPort: 80
