apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-exec
  name: liveness-exec
spec:
  containers:
  - image: registry.k8s.io/busybox
    name: liveness-exec
    args:
    - bin/sh
    - -c
    - touch /tmp/healthy; sleep30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
