apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-tcp
  name: liveness-tcp
spec:
  containers:
  - image: registry.k8s.io/goproxy:0.1
    name: liveness-tcp
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 3000
      initialDelaySeconds: 15
      periodSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
