apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    env: demo
    name: app-pod
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh','-c','echo app is running && sleep 3600']
    env:
    - name: FIRSTNAME
      value: 'ksk'
  initContainers:
  - name: init-my-service
    image: busybox:1.28
    command: ['sh','-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting;sleep 2;done']
  - name: init-my-db
    image: busybox:1.28
    command: ['sh','-c']
    args: ['until nslookup mydb.default.svc.cluster.local; do echo waiting;sleep 2;done']