apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
  affinity:
    nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: disktype
              operator: In
              values:
              - hdd
        - weight: 50
          preference:
            matchExpressions:
            - key: gpu
              operator: In
              values:
              - "true"
  dnsPolicy: ClusterFirst
  restartPolicy: Always