apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deployment
  labels:
    env: demo
spec:
  template: 
    metadata:
      name: nginx-pod
      labels:
        env: demo
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      env: demo
