apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mem-demo
  name: mem-demo-3
  namespace: mem-example
spec:
  containers:
  - image: polinux/stress
    name: mem-demo-ctr-3
    resources:
      requests:
        memory: "1000Gi"
      limits:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
