apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mem-demo
  name: mem-demo
  namespace: mem-example
spec:
  containers:
  - image: polinux/stress
    name: mem-demo-ctr-1
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "75M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
